### ISSUE TITLE
OpenAPI spec for webhook call

### ISSUE THREAD

**Issue by scothis** [vmware-tanzu/cartographer-conventions#59]
We expect third parties to implement the webhook contract in order to provide a convention. [OpenAPI](https://www.openapis.org) is the canonical way to describe a REST API. We should publish an OpenAPI spec for this endpoint.

**Comment by seagomezar** [comment]
@katmutua Is this done?

**Comment by scothis** [comment]
The spec is defined here https://github.com/vmware-tanzu/cartographer-conventions/blob/main/api/openapi-spec/conventions-server.yaml
