### ISSUE TITLE
Should containers without images be disallowed?

### ISSUE THREAD

**Issue by scothis** [vmware-tanzu/cartographer-conventions#76]
Today it's possible for a PodIntent resource to define a container within the template that doesn't include an image. Since there's no image, we can't lookup metadata or SBOMs. This is an edge case convention servers would need to be aware of and handle gracefully.

Should we require that all containers in a PodIntent have an image defined? Is there value in a convention being able to default the image? Other conventions that come before the convention that sets the image would be unable to participate in advising based on the content of the image.

**Comment by rszumlakowski** [comment]
Would it provide a good user experience for a Convention server to cause a whole supply chain to fail if it comes across a container with no image?

**Comment by rashedkvm** [comment]
> Individual conventions will need to accept that a container may not specify an image, and if it needs image metadata, not apply any config changes.

It is a no-op for the convention server if it requires image metadata.

**Comment by scothis** [comment]
> > Individual conventions will need to accept that a container may not specify an image, and if it needs image metadata, not apply any config changes.
> 
> It is a no-op for the convention server if it requires image metadata and shouldn't apply conventions.

Whichever way we go with the controller, it should be a no-op in the convention. The example currently isn't a no-op.

**Comment by rashedkvm** [comment]
Agreed. We will be updating Spring Boot Convention to handle this scenario.
